language: python

python:
  - "3.8"

notifications:
  email: false

os:
  - linux

before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  # anaconda
  - wget http://repo.continuum.io/miniconda/Miniconda3-3.8.3-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda config --add channels pypi
  - conda info -a
  - conda create -q -n test-environment "python=$TRAVIS_PYTHON_VERSION" pip cython coverage coveralls
  - source activate test-environment

install:
  - pip install -e ".[test]"

script:
  - pytest --cov=pysptk --cov-report xml -v tests/

after_success:
  - coveralls
