sudo: false
dist: xenial
language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

notifications:
  email: false

before_install:
  - sudo apt-get update
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget http://repo.continuum.io/miniconda/Miniconda-3.8.3-Linux-x86_64.sh -O miniconda.sh;
    else
      wget http://repo.continuum.io/miniconda/Miniconda3-3.8.3-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - pip install coveralls flake8
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda config --add channels pypi
  - conda info -a
  - deps='pip numpy scipy cython nose coverage six'
  - conda create -q -n test-environment "python=$TRAVIS_PYTHON_VERSION" $deps
  - source activate test-environment

install:
  - pip install -e .

script:
  - nosetests --with-coverage --cover-package=pysptk -v -w tests/
  - flake8

after_success:
  - coveralls
